default_config:

logger:
  default: info
  logs:
    custom_components.zte_tracker: debug
    homeassistant.components.device_tracker: debug

# Enable the debugger
debugpy:
  start: true
  wait: false
  port: 5678

# Example configuration for ZTE Tracker
# This will be replaced by config flow in production
zte_tracker:
  host: 192.168.1.1
  username: admin
  password: admin
  model: F6640
  interval_seconds: 60

# Enable frontend for testing
frontend:

# Enable history for testing
history:

# Enable logbook for testing  
logbook:

# Enable system health
system_health:

# Enable file editor for configuration
file_editor:
